AC_INIT(pa, 1.2.1)
AM_INIT_AUTOMAKE()
AC_CONFIG_HEADERS([conf.h])
AC_CONFIG_FILES([Makefile])
AC_PROG_CC(gcc)
AC_TYPE_INT32_T()
AC_TYPE_UINT32_T()
AC_CONFIG_FILES([Makefile])
AC_SUBST(prefix)
AC_SUBST(exec_prefix)
AC_SUBST(bindir)
AC_SUBST(sbindir)
AC_SUBST(libexecdir)
AC_SUBST(datarootdir)
AC_SUBST(datadir)
AC_SUBST(sysconfdir)
AC_SUBST(sharedstatedir)
AC_SUBST(localstatedir)
AC_SUBST(runstatedir)
AC_SUBST(includedir)
AC_SUBST(olincludedir)
AC_SUBST(docdir)
AC_SUBST(infodir)
AC_SUBST(docdir)
AC_SUBST(libdir)
AC_SUBST(lispdir)
AC_SUBST(localedir)
AC_SUBST(mandir)
AC_SUBST(srcdir)
AC_SUBST(musl_version)
