### @Author Cristofor Rotsching
all:pagrafnormal.s \
	pagraftranspus.s \
	padirector.s \
	pagrafproduct.s \
	pabuilder.s \
	pagrafnormal.o \
	pagraftranspus.o \
	padirector.o \
	pagrafproduct.o \
	pabuilder.o 
	@echo "clean $(PWD)"
	@echo "end of all $(PWD)"
clean: pagrafnormal.o pagraftranspus.o padirector.o pagrafproduct.o pabuilder.o pagrafnormal.s pagraftranspus.s padirector.s pagrafproduct.s pabuilder.s
	@echo "clean $(PWD)"
	rm pagrafnormal.o
	rm pagraftranspus.o
	rm padirector.o
	rm pagrafproduct.o
	rm pabuilder.o
	rm pagrafnormal.s
	rm pagraftranspus.s
	rm padirector.s
	rm pagrafproduct.s
	rm pabuilder.s

