## @Author Cristofor Rotsching
foo=PADrawingEditor.c PAShape.c PALine.c PATextShape.c PATextView.c
#bar := $(foo:.c=.o)
#include
C_INCLUDE_PATH+=./include
all:PADrawingEditor.o PAShape.o PALine.o PATextShape.o PATextView.o
	@echo "end of compile $(pwd)"
	@echo "end of all $(pwd)"
	@echo "end of assemble $(pwd)"
	@echo "end of compile $(pwd)"
clean:
	@echo "clean $(pwd)"
	@echo "end of clean"

#include builder/makefile
